### ISSUE TITLE
Utilisation hack

### ISSUE THREAD

**Issue by olpayras** [norecords/darksky-translate-alert#1]
Bonjour,

Très intéressant ton hack, mais je n'arrive pas à le faire fonctionner.

Voici ce que j'ai fais et qui ne fonctionne pas chez moi...

J'ai copié ton fichier htaccess.txt dans le root de mon site web meteo.payrastre.fr , déposé mod_dark.php dans le rep json, remplacé le département par mon département, mais mon alerte reste en anglais.

Mon apache a bien le rewrite activé, enfin il me semble.

Je ne vois pas ce qui cloche.

Egalement un nouveau message d'alerte à traduire: 

![Capture](https://user-images.githubusercontent.com/49792600/58310331-af738d80-7e06-11e9-9b3b-aff119853791.JPG)

Je suppose qu'il faut le rajouter dans dark_mod.php mais mes connaissances sont proches de 0 dans ce domaine…

Merci pour ton aide.

Olivier.

**Comment by norecords** [comment]
Salut Olivier,
As-tu renommé le fichier htaccess.txt en .htaccess ?
Merci pour cette traduction a ajouter.

**Comment by olpayras** [comment]
Ah super, oui, j'ai bien renommé le fichier. J'ai mis dark_mod.php dans le rep du site web dans le rep json, mais ca veut pas. On est bien d'accord qu'on dépose tout directement sur le site web ? de le fichier .htaccess dans la racine de mon virtualhost ? J'ai MQTT qui tourne sur weewx, ca serait pas ça qui poserait pb ? Pourtant j'ai redémarré apache, weewx, mais rien. Je comprends pas :(

**Comment by norecords** [comment]
Salut Olivier, c'est mon script qui n'est pas encore adapté au multiple alertes.
je suis sur ton site, tout est OK de ton côté.

**Comment by norecords** [comment]
@olpayras 
humm, finalement je crois que ton module apache rewrite n'est pas actif.
test 
`sudo a2enmod rewrite`
et
`sudo service apache restart`

**Comment by norecords** [comment]
@olpayras je viens de faire commit pour les alertes multiples et j'ai réordonnées les array pour que ce soit plus lisible.

**Comment by norecords** [comment]
@olpayras il te faut la directive AllowOverride All
Dans ton virtual host, sinon apache ne lit pas les htaccess

**Comment by olpayras** [comment]
Alors le soucis n'était pas sur l'activation du rewrite qui lui fonctionne, mais .htaccess n'est pas activé par défaut sur raspbian. Je l'ai activé mais c'est déconseillé pour des raisons de perfs. J'ai appliqué [ça](https://raspbian-france.fr/activer-fichiers-htaccess-raspbian/).

**Comment by norecords** [comment]
@olpayras repo à jour, tu peux essayer stp.

**Comment by norecords** [comment]
@olpayras tu as une erreur dans ta tradution:
`Risque d'inondation modéré à partir de 26 mai 2019 06:00`
devrait être
`Risque d'inondation modéré jusqu'au 26 mai 2019 06:00`

**Comment by norecords** [comment]
#0e3e531701ea45c6a3fbbc2a5cefcddfcfddb364

**Comment by olpayras** [comment]
Merci, je viens de corriger. J'ai mis ton dernier commit. On verra par la suite les nouveaux messages.

Merci pour tout.

**Comment by olpayras** [comment]
Fonctionne maintenant très bien. Je cloture.

**Comment by norecords** [comment]
@olpayras j'ai ouvert un issue pour l'ajout de traduction  #4 , et je viens de mettre à jour le dépot.
