### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by norecords** [norecords/darksky-translate-alert#4]
Ajout de vent violent, et modification des libéllés pour correspondre avec ceux de Météo France.

Added `Moderate Wind Warning` and modified labels to fit with Météo France.

**Comment by olpayras** [comment]
Impec, je mets à jour. ;)

**Comment by olpayras** [comment]
Salut, nouvelle alerte chez moi 
:
 "Moderate High-temperature Warning"

Correspond à "Vigilance jaune canicule"

**Comment by olpayras** [comment]
Encore une nouvelle :

Severe High-temperature Warning -> Vigilance orange canicule

Vive la canicule !!!

**Comment by norecords** [comment]
@olpayras , à jour ;)

**Comment by olpayras** [comment]
Merci bcp. Je suppose qu'on peut en déduire les autres vigilances orange, mais peut-être va-t-on attendre d'avoir l'orthographe exacte, sait-on jamais ?

**Comment by norecords** [comment]
Effectivement je pense qu'on peut d'ores et déjà traduire les vigilances orange, au pire elles ne seront pas traduites si l'orthographe ne correspond pas.

**Comment by norecords** [comment]
@olpayras dernière mise à jour avec toutes les alertes jaune/orange/rouge.
Il ne manque plus que les alertes neige/verglas.

**Comment by olpayras** [comment]
Parfait. Pour la neige/verglas c'est pas pour de suite !!! Mais cet hiver, forcément, il y aura ça chez moi car un bout du département est à plus de 800m et il y a souvent des problèmes pour y accéder avec la neige.

**Comment by norecords** [comment]
Salut,
petite mise à jour avec l'ajout des traductions pour "vagues-submersion".

**Comment by olpayras** [comment]
Et voilà, ca arrive :

Nouvelles alertes à traduire neige-verglas :

```
"Moderate Snow-ice Warning",
"Severe Snow-ice Warning",
"Extreme Snow-ice Warning"
```

**Comment by norecords** [comment]
@olpayras Merci ;)

**Comment by norecords** [comment]
d2a26e8
J'ai vu qu'il existe aussi alerte Grand-froid pendant l'hiver.

wait and see

**Comment by olpayras** [comment]
Oui, ca doit être sur le même modèle que les alertes canicules. Il faut qu'il fasse vraiment froid pour que ca se déclenche. Ca peut arriver chez nous, mais c'est très rare la dernière fois c'était en 2012 ou on a eu des températures moyennes négatives sur 15 jours. Je n'avais à l'époque pas de station connectée.
